---
  - name: Update all installed packages using APT module
    apt:
      name: '*'
      state: latest
      update_cache: yes
      only_upgrade: yes
      cache_valid_time: 86400 # 1 day
    register: apt_update_status
    tags: installation, latest

  - name: Install the latest version of unbound, dnsutils & python-setuptools
    ansible.builtin.package:
      name:
        - unbound
        - dnsutils
      state: latest
  
  - name: Copy 'unbound' config file to remote host ## https://docs.pi-hole.net/guides/dns/unbound/#configure-unbound ##
    copy:
      src: ../files/pi-hole.conf
      dest: "{{ unbound_directory }}/pi-hole.conf"
    notify: Restart unbound service

  - name: Test unbound functionality using dig
    ansible.builtin.debug:
      msg: "Querying loopback for IPv4 address for pi-hole.net. produces {{ lookup('community.general.dig', 'pi-hole.net', '@127.0.0.1:5335') }}"