
  - name: Update all installed packages using APT module
    apt:
      name: '*'
      state: latest
      update_cache: yes
      only_upgrade: yes
      cache_valid_time: 86400 #One day
    register: apt_update_status
    tags: installation, latest

  - name: Remove packages not needed anymore
    apt:
      autoremove: yes
    tags: installation, prune
