---
- name: Install fail2ban - Debian
  apt:
    name: fail2ban
    state: present
  when: ansible_os_family == 'Debian'
  become: true

- name: Install fail2ban - RedHat
  package:
    name: fail2ban
    state: present
  when: ansible_os_family == 'RedHat'

- name: Start fail2ban
  service:
    name: fail2ban
    state: started
  become: true

- name: Enable fail2ban service
  service:
    name: fail2ban
    enabled: true
  become: true

- name: Check auth.log exists
  stat:
    path: /var/log/auth.log
  register: stat_result

- debug:
    msg: "auth.log exists, move on..."
  when: stat_result.stat.exists

- name: Install rsyslog
  package:
    name: rsyslog
    state: present
  when: stat_result.stat.exists == False